# Generated by Django 5.2.5 on 2025-09-11 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Codigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=30)),
                ('code', models.CharField(max_length=6)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiaSemanaAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('segunda', 'segunda'), ('terca', 'terca'), ('quarta', 'quarta'), ('quinta', 'quinta'), ('sexta', 'sexta')], max_length=7, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CalendarioLetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_inicio', models.DateField(null=True)),
                ('data_fim', models.DateField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendarios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataImportante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('detalhes', models.CharField(default='', max_length=255)),
                ('dia_letivo', models.BooleanField(default=True)),
                ('calendario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datas', to='planner.calendarioletivo')),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('objetivo', models.TextField(blank=True)),
                ('ementa', models.TextField(blank=True)),
                ('periodo', models.CharField(choices=[('semestral', 'semestral'), ('anual', 'anual')], max_length=20)),
                ('carga_horaria', models.PositiveIntegerField()),
                ('calendario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='planner.calendarioletivo')),
                ('dias_aulas', models.ManyToManyField(blank=True, to='planner.diasemanaaula')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlanoAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('titulo', models.CharField(max_length=100)),
                ('objetivos', models.TextField(default='')),
                ('conteudos', models.TextField(default='')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('criado', 'Criado'), ('nao_planejada', 'Não planejada'), ('planejada', 'Planejada'), ('material_em_desenvolvimento', 'Material em desenvolvimento'), ('material_concluido', 'Material concluído')], default='criado', max_length=50)),
                ('num_aulas', models.PositiveIntegerField(default=2)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos', to='planner.disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('avaliacao', 'Avaliação'), ('prova', 'Prova'), ('trabalho', 'Trabalho'), ('recuperacao', 'Recuperação'), ('seminario', 'Seminário')], max_length=50)),
                ('etapa', models.CharField(blank=True, choices=[], default='', max_length=50, null=True)),
                ('status', models.CharField(choices=[('nao_planejada', 'Não planejada'), ('planejada', 'Planejada'), ('em_elaboracao', 'Em elaboração'), ('elaborada', 'Elaborada'), ('aplicada', 'Aplicada'), ('corrigida', 'Corrigida'), ('agendada', 'Agendada')], default='agendada', max_length=50)),
                ('data', models.DateField()),
                ('identificador', models.CharField(max_length=100)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='planner.disciplina')),
                ('plano_aula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='planner.planoaula')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conta_ativada', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=50)),
                ('descricao', models.TextField()),
                ('prazo', models.DateField()),
                ('status', models.CharField(choices=[('criada', 'Criada'), ('em_andamento', 'Em andamento'), ('pendente', 'Pendente'), ('concluida', 'Concluída')], default='criada', max_length=50)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='planner.disciplina')),
                ('plano_aula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='planner.planoaula')),
            ],
        ),
    ]
