# Generated by Django 5.2.5 on 2025-09-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_tokenativacaoconta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='dias_aulas',
            field=models.ManyToManyField(blank=True, related_name='dias', to='planner.diasemanaaula'),
        ),
    ]
