# Generated by Django 5.2.5 on 2025-09-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_alter_disciplina_dias_aulas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='dias_aulas',
            field=models.ManyToManyField(blank=True, to='planner.diasemanaaula'),
        ),
    ]
