# Generated by Django 5.2.5 on 2025-09-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_alter_disciplina_dias_aulas'),
    ]

    operations = [
        migrations.AddField(
            model_name='diasemanaaula',
            name='data',
            field=models.DateField(null=True, unique=True),
        ),
    ]
