# Generated by Django 5.2.5 on 2025-09-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_diasemanaaula_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diasemanaaula',
            name='dia',
            field=models.CharField(choices=[('segunda', 'segunda'), ('terca', 'terca'), ('quarta', 'quarta'), ('quinta', 'quinta'), ('sexta', 'sexta')], max_length=7),
        ),
    ]
