# Generated by Django 5.2.5 on 2025-09-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_alter_diasemanaaula_dia'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='aviso',
            field=models.CharField(default='', max_length=100),
        ),
    ]
