# Generated by Django 5.2.5 on 2025-09-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_disciplina_aviso'),
    ]

    operations = [
        migrations.AddField(
            model_name='diasemanaaula',
            name='dia_letivo',
            field=models.BooleanField(default=False),
        ),
    ]
