# Generated by Django 5.2.5 on 2025-09-15 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0008_diasemanaaula_dia_letivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diasemanaaula',
            name='dia_letivo',
        ),
    ]
