# Generated by Django 5.2.5 on 2025-10-01 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0009_remove_diasemanaaula_dia_letivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='planoaula',
            name='dia_aula_selecionado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planner.diasemanaaula'),
        ),
    ]
