# Generated by Django 5.2.5 on 2025-10-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0010_planoaula_dia_aula_selecionado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diasemanaaula',
            name='data',
            field=models.DateField(null=True),
        ),
    ]
