# Generated by Django 5.2.5 on 2025-10-01 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0011_alter_diasemanaaula_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planoaula',
            name='dia_aula_selecionado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planner.diasemanaaula'),
        ),
    ]
