# Generated by Django 5.2.5 on 2025-10-01 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0012_alter_planoaula_dia_aula_selecionado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planoaula',
            name='dia_aula_selecionado',
        ),
    ]
