# Generated by Django 5.2.5 on 2025-10-01 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0013_remove_planoaula_dia_aula_selecionado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='dias_aulas',
        ),
        migrations.DeleteModel(
            name='DiaSemanaAula',
        ),
    ]
