# Generated by Django 5.2.5 on 2025-11-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0014_remove_disciplina_dias_aulas_delete_diasemanaaula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokenativacaoconta',
            name='user',
        ),
        migrations.AddField(
            model_name='tokenativacaoconta',
            name='email',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
