# Generated by Django 4.2.7 on 2025-11-21 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0015_remove_tokenativacaoconta_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conteudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('abordado', models.BooleanField(default=False)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conteudos', to='planner.disciplina')),
                ('plano_aula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conteudos_abordados', to='planner.planoaula')),
            ],
            options={
                'verbose_name': 'Conteúdo',
                'verbose_name_plural': 'Conteúdos',
                'ordering': ['ordem'],
            },
        ),
    ]
