# Generated by Django 4.2.7 on 2025-11-21 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0017_objetivo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conteudo',
            options={'ordering': ['id'], 'verbose_name': 'Conteúdo', 'verbose_name_plural': 'Conteúdos'},
        ),
        migrations.AlterModelOptions(
            name='objetivo',
            options={'ordering': ['id'], 'verbose_name': 'Objetivo', 'verbose_name_plural': 'Objetivos'},
        ),
        migrations.RemoveField(
            model_name='conteudo',
            name='ordem',
        ),
        migrations.RemoveField(
            model_name='objetivo',
            name='ordem',
        ),
    ]
