# Generated by Django 4.2.7 on 2025-11-21 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0018_alter_conteudo_options_alter_objetivo_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ementa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('abordado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Ementa',
                'verbose_name_plural': 'Ementas',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='ementa',
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='objetivo',
        ),
        migrations.DeleteModel(
            name='Conteudo',
        ),
        migrations.AddField(
            model_name='ementa',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ementas', to='planner.disciplina'),
        ),
        migrations.AddField(
            model_name='ementa',
            name='plano_aula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ementas_abordadas', to='planner.planoaula'),
        ),
    ]
