# Generated by Django 5.2.5 on 2026-01-31 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0019_ementa_remove_disciplina_ementa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokenativacaoconta',
            name='expiracao',
        ),
    ]
