# Generated by Django 5.2.5 on 2026-01-31 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0020_remove_tokenativacaoconta_expiracao'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoImportante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('detalhes', models.CharField(default='', max_length=255)),
                ('eh_letivo', models.BooleanField(default=True)),
                ('calendario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos', to='planner.calendarioletivo')),
            ],
        ),
    ]
