# Generated by Django 6.0.2 on 2026-03-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0021_periodoimportante'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoRecuperacaoSenha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=30)),
                ('code', models.CharField(max_length=6)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Codigo',
        ),
        migrations.AlterField(
            model_name='tokenativacaoconta',
            name='email',
            field=models.EmailField(blank=True, max_length=64, unique=True),
        ),
    ]
