# Generated by Django 6.0.2 on 2026-03-12 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0022_codigorecuperacaosenha_delete_codigo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokenativacaoconta',
            name='email',
        ),
        migrations.AddField(
            model_name='tokenativacaoconta',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professor', to='planner.professor'),
        ),
    ]
