# Generated by Django 6.0.2 on 2026-03-13 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0023_remove_tokenativacaoconta_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codigorecuperacaosenha',
            name='email',
        ),
        migrations.AddField(
            model_name='codigorecuperacaosenha',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codigo_professor', to='planner.professor'),
        ),
    ]
