# Generated by Django 6.0.2 on 2026-03-13 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0024_remove_codigorecuperacaosenha_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigorecuperacaosenha',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='planner.professor'),
        ),
    ]
